app/frontend/containers/DashboardContainer.js, app/frontend/containers/NavBarContainer.js, app/frontend/containers/TimelineContainer.js, app/frontend/ui/App.jsx, app/frontend/ui/Home.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/SpotDetail.jsx, app/frontend/ui/Timeline.jsx, routes.js
=> Separate home timeline

app/frontend/ui/Timeline.jsx
=> Fix timeline styles

app/controllers/Users.js, app/frontend/actionTypes/index.js, app/frontend/actions/fetchMyProfile.js, app/frontend/containers/ApiClient.js, app/frontend/containers/LoginContainer.js, app/frontend/containers/TimelineContainer.js, app/frontend/reducers/appReducer.js, app/frontend/ui/Timeline.jsx, app/models/QoodishClient.js, app/models/errors/FetchUserFailed.js, routes.js
タイムライン画面にプロフィールカードを表示。
現状カードからのアクションは何もないが、そのうちプロフィール画面に飛ばすようにする。
=> Add user profile card to timeline page

app/frontend/containers/TimelineContainer.js, app/frontend/ui/Timeline.jsx
ごちゃっとしてタイムライン本体が見難くなったので外した。
プロフィール取得のインターフェイスはプロフィール画面で使うので残す。
=> Remove profile and following maps from timeline

app/frontend/containers/LoginContainer.js, app/frontend/containers/ReviewCardContainer.jsx, app/frontend/containers/SettingsContainer.js, app/frontend/ui/BlockUi.jsx, app/frontend/ui/Dashboard.jsx, app/frontend/ui/Login.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/Settings.jsx, app/frontend/ui/Timeline.jsx, app/views/index.html
=> Tweak mobile layout

app/frontend/ui/Home.jsx, app/frontend/ui/Maps.jsx
=> Tweak mobile grid tile styles

app/controllers/Auth.js, app/controllers/Collaborators.js, app/controllers/Devices.js, app/controllers/Follows.js, app/controllers/InappropriateContents.js, app/controllers/Maps.js, app/controllers/Reviews.js, app/controllers/Spots.js, app/controllers/UserMaps.js, app/controllers/Users.js, app/frontend/containers/TimelineContainer.js, app/middlewares/detectLocale.js, app/models/Utils.js, index.js, routes.js
=> Refactoring koa

.gitignore, Dockerfile, app/service_workers/firebase-messaging-sw.js, package.json, webpack.config.js
Service Worker を Webpack で使ってビルドするようにしました。
ついでに Node と Yarn のバージョンを上げました。
=> Build service worker by webpack

app/frontend/containers/EditReviewDialogContainer.js, app/frontend/reducers/reviewsReducer.js
レビューの画像を削除できない問題を修正しました。
ついでにダイアログを閉じる際の挙動を微修正しました。
=> Fix delete review image

app/frontend/ui/SpotDetail.jsx
モバイルサイズの場合はスポットの詳細を bottom seat で表示するようにしました。
=> Show spot detail with bottom seat when mobile

app/frontend/containers/MapDetailContainer.js, app/frontend/containers/MapSummaryContainer.js, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/SpotDetail.jsx
モバイル時のマップ画面でマップ詳細が表示されていなかったところを、 bottom seat を使って表示するようにしました。
=> Map detail bottom seat

package.json, yarn.lock
react-places-autocomplete を誤って削除してしまったので改めて追加しました。
=> Fix react-places-autocomplete

app/frontend/containers/DeleteReviewDialogContainer.js, app/frontend/containers/EditReviewDialogContainer.js, app/frontend/reducers/reviewsReducer.js, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/PlaceSelectDialog.jsx, app/frontend/ui/SpotDetail.jsx
レビュー編集時に画像が勝手に削除されてしまう問題を修正しました。
ついでにスタイルを微修正しました。
=> Fix review image update

app/frontend/ui/MapSummary.jsx, app/frontend/ui/SpotDetail.jsx
=> Correct direction of arrow icon

app/frontend/ui/PlaceSelectDialog.jsx
Place ID が取得できなくなっていたので修正しました。
=> Fix missing place ID

app/frontend/containers/MapSummaryContainer.js
Review クリック時にマップの中心をスポットの位置に移動するように修正しました。
=> Move map center on click review

app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/ReviewDialog.jsx
=> Tweak map bottom card

app/frontend/containers/DeleteReviewDialogContainer.js, app/frontend/containers/JoinMapDialogContainer.js, app/frontend/containers/LeaveMapDialogContainer.js, app/frontend/containers/MapDetailContainer.js, app/frontend/containers/MapSummaryContainer.js, app/frontend/containers/SpotDetailContainer.js, app/frontend/index.js, app/frontend/reducers/mapDetailReducer.js, app/frontend/reducers/mapSummaryReducer.js, app/frontend/reducers/spotDetailReducer.js, app/frontend/ui/App.jsx, app/frontend/ui/JoinMapDialog.jsx, app/frontend/ui/LeaveMapDialog.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDialog.jsx, app/frontend/ui/SpotDetail.jsx, app/models/errors/JoinMapFailed.js, app/models/errors/LeaveMapFailed.js
=> Replace join with follow

app/frontend/containers/NavBarContainer.js, app/frontend/ui/MapDetail.jsx, app/frontend/ui/NavBar.jsx
=> Refactor notification

app/frontend/ui/Discover.jsx, app/frontend/ui/Login.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDialog.jsx
=> Landing page

.env.sample, app/frontend/containers/ReviewCardContainer.js, app/frontend/ui/Login.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDialog.jsx, webpack.config.js
=> Fix landing page

app/controllers/Devices.js, app/frontend/containers/ApiClient.js, app/frontend/containers/NavBarContainer.js, app/models/QoodishClient.js, app/models/errors/DeleteDeviceFailed.js, routes.js
ログアウト時に (現在のユーザーの) FCM registration token を削除するように修正。
=> Delete registration token when signed out

app/frontend/containers/PrivacyContainer.js, app/frontend/containers/TermsContainer.js, app/frontend/ui/App.jsx, app/frontend/ui/Login.jsx, app/frontend/ui/Privacy.jsx, app/frontend/ui/Terms.jsx, routes.js
=> Add terms of service and privacy policy

Dockerfile-dev, Dockerfile-prod
=> Upgrade node 8.9.4

package.json
=> Fix upgrade node 8.9.4

app/frontend/containers/DiscoverContainer.js, app/frontend/containers/MapsContainer.js, app/frontend/containers/PlaceSelectDialogContainer.js, app/frontend/ui/App.jsx, app/frontend/ui/DeleteAccountDialog.jsx, app/frontend/ui/DeleteMapDialog.jsx, app/frontend/ui/DeleteReviewDialog.jsx, app/frontend/ui/Discover.jsx, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/IssueDialog.jsx, app/frontend/ui/JoinMapDialog.jsx, app/frontend/ui/LeaveMapDialog.jsx, app/frontend/ui/LikesDialog.jsx, app/frontend/ui/Login.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/PlaceSelectDialog.jsx, app/frontend/ui/Privacy.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDialog.jsx, app/frontend/ui/SpotDetail.jsx, app/frontend/ui/Terms.jsx, app/frontend/ui/Toast.jsx, package.json, yarn.lock
Material-UI のバージョンを上げました。ついでに yarn upgrade しました。
=> Upgrade Material-UI & packages

app/frontend/ui/Discover.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/SpotDetail.jsx
=> Fix styles

.babelrc, index.js, package.json, webpack.config.js, yarn.lock
babel 7 で import する必要がなくなっていました。
参考
https://qiita.com/shisama/items/88080011bbc69e3e620b
=> Fix babel-polyfill settings

app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx
=> Fix map bottom nav styles

app/frontend/containers/CreateMapDialogContainer.js, app/frontend/containers/EditMapDialogContainer.js, app/frontend/containers/ReviewCardContainer.js, app/frontend/ui/BlockUi.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/ReviewDialog.jsx
=> Fix edit report

public/manifest.json
PWA 対応のため manifest.json を更新しました。
=> Update manifest.json for PWA

app/frontend/containers/ReviewCardContainer.js, app/frontend/ui/Discover.jsx, app/frontend/ui/ReviewCard.jsx
=> Fix routing

app/frontend/containers/MapDetailContainer.js, app/frontend/containers/MapSummaryContainer.js, app/frontend/containers/ReviewDialogContainer.js, app/frontend/containers/SpotCardContainer.js, app/frontend/reducers/spotCardReducer.js, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDetail.jsx, app/frontend/ui/ReviewDialog.jsx, app/frontend/ui/SpotCard.jsx, app/frontend/ui/SpotDetail.jsx
=> Fix map tab routing

app/frontend/ui/ReviewDialog.jsx, public/manifest.json
Android 向けに manifest 修正。
https://developers.google.com/web/fundamentals/app-install-banners/?hl=ja
=> Fix manifest

app/frontend/containers/BottomNavContainer.jsx, app/frontend/containers/CreateMapDialogContainer.js, app/frontend/containers/DeleteReviewDialogContainer.js, app/frontend/containers/EditMapDialogContainer.js, app/frontend/containers/EditReviewDialogContainer.js, app/frontend/containers/SpotDetailContainer.js, app/frontend/reducers/spotDetailReducer.js, app/frontend/ui/App.jsx, app/frontend/ui/BottomNav.jsx, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDetail.jsx, app/frontend/ui/SpotCard.jsx, app/frontend/ui/SpotDetail.jsx, app/frontend/ui/Timeline.jsx, public/manifest.json
モバイル画面のときに bottom navigation を表示するようにしました。
その他 style の微修正を行いました。
=> Bottom navigation

app/frontend/containers/PlaceSelectDialogContainer.js, app/frontend/containers/ReviewCardContainer.js, app/frontend/ui/Discover.jsx, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/LikesDialog.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/PlaceSelectDialog.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDialog.jsx
Review 編集時に画像が表示されない問題を修正しました。
その他 style の修正を行いました。
=> Fix drawing review image

app/frontend/containers/MapsContainer.js, app/frontend/containers/TimelineContainer.js, app/frontend/ui/Maps.jsx, app/frontend/ui/PlaceSelectDialog.jsx, app/frontend/ui/Timeline.jsx
リソースがない時の表示を改善しました。
また、タイムライン上部にレビュー投稿フォームを開くカードを追加しました。
=> Improve initial timeline

app/views/index.html, webpack.config.js
=> Add default meta tags

firebase.json, webpack.config.js
確実にルートディレクトリから bundle.js が読み込まれるように修正しました。
=> Fix refer bundlejs

app/frontend/locales/en.json, app/frontend/locales/ja.json, app/frontend/ui/Timeline.jsx
=> multilingualize Timeline.jsx

app/frontend/containers/CopyReviewDialogContainer.js, app/frontend/containers/Utils.js, cors.json
レポートのイメージ (オブジェクト) にコピーがされていなかったので修正しました。
https://firebase.google.com/docs/storage/web/download-files?hl=ja
=> Copy review image

app/frontend/ui/App.jsx
=> Scroll top on route change

app/frontend/containers/NavBarContainer.js, app/frontend/ui/MapSummary.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/NavBar.jsx
マップ詳細画面のロード時にスケルトンスクリーンを表示するようにしました。
=> Skelton screen

app/frontend/containers/DiscoverContainer.js, app/frontend/ui/App.jsx, app/frontend/ui/Discover.jsx, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/PlaceSelectDialog.jsx, app/frontend/ui/ReviewDetail.jsx, app/frontend/ui/SpotDetail.jsx, app/functions/Utils.js, app/functions/index.js, app/views/index.html, functions/metadata.html
=> Fix metadata

app/frontend/containers/CreateMapDialogContainer.js, app/frontend/containers/EditReviewDialogContainer.js, app/frontend/containers/LoginContainer.js, app/frontend/containers/ReviewCardContainer.js, app/frontend/reducers/sharedReducer.js, app/views/index.html, webpack.config.js
=> Introduce Google Analytics

app/frontend/reducers/sharedReducer.js, webpack.config.js
React によるページ遷移時に正しくページビューがカウントされていなかったので修正。
=> Fix Google Analytics

app/frontend/reducers/sharedReducer.js, app/frontend/ui/Discover.jsx, app/frontend/ui/Login.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/Privacy.jsx, app/frontend/ui/ReviewDetail.jsx, app/frontend/ui/Settings.jsx, app/frontend/ui/SpotDetail.jsx, app/frontend/ui/Terms.jsx, app/frontend/ui/Timeline.jsx
path と title が一致していなかったので componentWillMount のタイミングでページビューをカウントするように修正しました。
=> Fix gtag page title

app/frontend/ui/NavBar.jsx
通知欄のメッセージが出力されなくなっていたので修正しました。
=> Fix notification center

app/frontend/ui/ReviewDetail.jsx
=> Fix page_path for GA

app/frontend/containers/EditReviewDialogContainer.js, app/frontend/ui/EditReviewDialog.jsx
=> Edit place for review

app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/EditReviewDialog.jsx
=> Change upper limit of comment length to 200

app/frontend/ui/ReviewCard.jsx, package.json, yarn.lock
レポートのコメントに書いた URL がリンクとして機能するようにしました。
=> Introduce twitter-text

app/frontend/containers/CreateMapDialogContainer.js, app/frontend/containers/DeleteReviewDialogContainer.js, app/frontend/containers/DiscoverContainer.js, app/frontend/containers/InvitesContainer.js, app/frontend/containers/MapSummaryContainer.js, app/frontend/containers/MapsContainer.js, app/frontend/containers/NavBarContainer.js, app/frontend/containers/ReviewCardContainer.js, app/frontend/containers/SpotCardContainer.js, app/frontend/containers/SpotDetailContainer.js, app/frontend/reducers/sharedReducer.js, app/frontend/ui/NavBar.jsx
Appbar 上の「戻るボタン」を押した際に、直前のページ履歴が存在しなかった場合はルート (/) に遷移するようにしました。
=> Fix back button

app/frontend/ui/CopyReviewDialog.jsx, app/frontend/ui/DeleteAccountDialog.jsx, app/frontend/ui/DeleteMapDialog.jsx, app/frontend/ui/DeleteReviewDialog.jsx, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/InviteTargetDialog.jsx, app/frontend/ui/IssueDialog.jsx, app/frontend/ui/JoinMapDialog.jsx, app/frontend/ui/LeaveMapDialog.jsx, app/frontend/ui/LikesDialog.jsx, app/frontend/ui/PlaceSelectDialog.jsx, app/frontend/ui/ReviewDialog.jsx
component が unmount されるタイミングで各種ダイアログをクローズするように修正しました。
=> Close dialog on unmount

app/frontend/reducers/reviewsReducer.js
レポート編集ダイアログを閉じた際に、選択済みのプレイスをクリアするように修正しました。
=> Clear selected place

app/frontend/containers/MapSummaryContainer.js, app/frontend/containers/ReviewCardContainer.js
レポート及びマップを Twitter でシェアする際のメッセージを修正しました。
=> Fix share message

app/frontend/ui/NavBar.jsx
=> Fix notification text

app/frontend/ui/App.jsx, app/frontend/ui/DeleteAccountDialog.jsx, app/frontend/ui/DeleteMapDialog.jsx, app/frontend/ui/DeleteReviewDialog.jsx, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/IssueDialog.jsx, app/frontend/ui/JoinMapDialog.jsx, app/frontend/ui/LeaveMapDialog.jsx, app/frontend/ui/LikesDialog.jsx, app/frontend/ui/Login.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDetail.jsx, app/frontend/ui/SpotDetail.jsx, app/views/index.html
コンソールに出ていた JS エラーを出来る限り消しました。
その他 style 微修正。
=> Fix js errors

app/frontend/ui/MapDetail.jsx, app/frontend/ui/NavBar.jsx
=> Fix routes

app/frontend/reducers/mapDetailReducer.js, app/frontend/reducers/mapsReducer.js, app/frontend/reducers/reviewsReducer.js, app/frontend/reducers/settingsReducer.js, app/frontend/reducers/sharedReducer.js, app/frontend/ui/App.jsx, app/frontend/ui/CopyReviewDialog.jsx, app/frontend/ui/DeleteAccountDialog.jsx, app/frontend/ui/DeleteMapDialog.jsx, app/frontend/ui/DeleteReviewDialog.jsx, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/InviteTargetDialog.jsx, app/frontend/ui/IssueDialog.jsx, app/frontend/ui/JoinMapDialog.jsx, app/frontend/ui/LeaveMapDialog.jsx, app/frontend/ui/LikesDialog.jsx, app/frontend/ui/Login.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/PlaceSelectDialog.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDialog.jsx, app/frontend/ui/SpotDetail.jsx, app/frontend/ui/Timeline.jsx
=> Fix images and dialogs

app/frontend/containers/EditReviewDialogContainer.js, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/ReviewDialog.jsx
=> Fix duplicate edit review dialog

app/frontend/ui/App.jsx, app/frontend/ui/DeleteAccountDialog.jsx, app/frontend/ui/DeleteMapDialog.jsx, app/frontend/ui/DeleteReviewDialog.jsx, app/frontend/ui/Discover.jsx, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/InviteTargetDialog.jsx, app/frontend/ui/Invites.jsx, app/frontend/ui/IssueDialog.jsx, app/frontend/ui/JoinMapDialog.jsx, app/frontend/ui/LeaveMapDialog.jsx, app/frontend/ui/Login.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/PlaceSelectDialog.jsx, app/frontend/ui/Privacy.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDetail.jsx, app/frontend/ui/ReviewDialog.jsx, app/frontend/ui/Settings.jsx, app/frontend/ui/SpotCard.jsx, app/frontend/ui/SpotDetail.jsx, app/frontend/ui/Terms.jsx, app/frontend/ui/Timeline.jsx, package.json, yarn.lock
=> Material-UI v1.0.0-beta.38

app/frontend/ui/EditReviewDialog.jsx
=> Fix add image button

app/functions/index.js, functions/package-lock.json, functions/package.json
画像をアップロードした際にサムネイル版の画像を生成するようにしました。
参考
https://firebase.google.com/docs/functions/use-cases?hl=ja
https://firebase.google.com/docs/functions/gcp-storage-events?hl=ja
https://github.com/firebase/functions-samples/blob/master/quickstarts/thumbnails/functions/index.js
=> Add function to generate thumbnails

app/frontend/containers/EditReviewDialogContainer.js, app/frontend/ui/CopyReviewDialog.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/SpotDetail.jsx
=> Refer thumbnails

app/frontend/containers/CopyReviewDialogContainer.js, app/frontend/containers/DeleteReviewDialogContainer.js, app/frontend/containers/EditReviewDialogContainer.js, app/views/index.html
AWS S3 から GCS に画像を移送したことに伴い不要になったコードを削除しました。
=> Remove s3 image

app/frontend/index.js, functions/hosting/manifest.json, functions/hosting/sw.js
Service Worker を register しました (中身は空)。
=> Introduce service worker

app/frontend/reducers/mapsReducer.js
マップ新規作成/編集ダイアログを閉じた際に選択済みの拠点をクリアするようにしました。
=> Clear selected map base

package.json, yarn.lock
=> Upgrade to webpack 4

app/functions/index.js
レポートの thumbnail をキャッシュするようにしました。
=> Cache thumbnails

app/frontend/ui/Discover.jsx
Discover ページの ReviewCard のレイアウトを変更しました。
=> Update review card on discover

app/frontend/ui/Discover.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/Maps.jsx
マップのタイプを表すアイコンを表示しました。
* Private
* Shared
* Personal
=> Show map type icons

app/frontend/ui/Discover.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/Maps.jsx
マップタイプアイコンを微修正しました。
* 色を変更
* サイズを変更
* tooltip を追加
=> Tweak map type icons

app/frontend/ui/LikesDialog.jsx, app/frontend/ui/ReviewsDialog.jsx, app/frontend/ui/SpotCard.jsx
=> Fix spot card

app/frontend/containers/MapSummaryContainer.js, app/frontend/containers/ReviewsDialogContainer.js, app/frontend/ui/MapSummary.jsx, app/frontend/ui/ReviewDialog.jsx, app/frontend/ui/ReviewsDialog.jsx, app/frontend/ui/SpotCard.jsx
マップ詳細画面からレポートを開く際はダイアログを使うようにしました。
=> Use review dialogs

app/frontend/ui/ReviewDialog.jsx
Review Dialog 上の AppBar が固定されない問題を修正しました。
=> Fix review dialog

app/frontend/containers/DiscoverContainer.js, app/frontend/containers/ReviewsDialogContainer.js, app/frontend/containers/SpotCardContainer.js, app/frontend/containers/SpotDetailContainer.js, app/frontend/ui/LikesDialog.jsx, app/frontend/ui/ReviewsDialog.jsx, app/frontend/ui/SpotCard.jsx, app/frontend/ui/SpotDetail.jsx
=> Update spot card

app/frontend/containers/MapDetailContainer.js, app/frontend/containers/MapsContainer.js, app/frontend/ui/MapDetail.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/SpotCard.jsx, package.json, yarn.lock
タブをスワイプで切り替えられるようにしました。
また、メニューもスワイプで開閉できるようにしました。
https://github.com/oliviertassinari/react-swipeable-views
https://material-ui-next.com/demos/drawers/#swipeable-temporary-drawer
=> Swipeable views

app/frontend/ui/Login.jsx, package.json, yarn.lock
Facebook ページと GitHub リポジトリのリンクを LP に設置しました。
=> Add FB page & GitHub link

app/frontend/containers/MapDetailContainer.js, app/frontend/containers/MapSummaryContainer.js, app/frontend/containers/MapsContainer.js, app/frontend/containers/NavBarContainer.js, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/NavBar.jsx
タブ切り替え時にいちいち history に記録されて、戻るボタンを押してもいつまでたっても元いたページに戻れなくなってしまうのが鬱陶しいので直しました。
=> Remove hash routing

app/frontend/actionTypes/index.js, app/frontend/actions/hideMapDetailTab.js, app/frontend/actions/showMapDetailTab.js, app/frontend/containers/EditReviewDialogContainer.js, app/frontend/containers/MapDetailContainer.js, app/frontend/containers/MapSummaryContainer.js, app/frontend/containers/NavBarContainer.js, app/frontend/reducers/mapDetailReducer.js, app/frontend/reducers/sharedReducer.js, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/Notifications.jsx, app/frontend/ui/SpotDetail.jsx
モバイル画面におけるマップ詳細 ↔ Google マップの切り替えを改善しました (タブ廃止)。
=> Update map detail

app/frontend/ui/DeleteAccountDialog.jsx, app/frontend/ui/DeleteMapDialog.jsx, app/frontend/ui/DeleteReviewDialog.jsx, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/InviteTargetDialog.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/PlaceSelectDialog.jsx
モバイル画面においてマップを drawer で開くようにしました。
=> Map drawer

app/frontend/ui/MapDetail.jsx, app/frontend/ui/NavBar.jsx
=> Fix map drawer style

app/frontend/containers/LikesDialogContainer.js, app/frontend/ui/Profile.jsx
いいねした人一覧からもプロフィール画面に飛べるようにしました。
=> Profile page from likes

app/frontend/ui/BottomNav.jsx
bottom nav action がはみ出てしまう問題を修正しました。
=> Fix overflow bottom nav

app/frontend/containers/UserProfileContainer.js, app/frontend/ui/App.jsx, app/frontend/ui/Profile.jsx
他のユーザーのプロフィールを表示後に自分のプロフィール画面に遷移すると、画面がリフレッシュされない問題を修正しました。
=> Fix user profile

app/frontend/containers/LikesDialogContainer.js, app/frontend/containers/MapSummaryContainer.js, app/frontend/containers/ReviewCardContainer.js
プロフィール画面からバックボタンを押したときに常にホーム画面に戻ってしまう問題を修正しました。
=> Fix profile routing

app/frontend/containers/CreateMapButtonContainer.js, app/frontend/containers/CreateReviewButtonContainer.js, app/frontend/containers/MapCollectionContainer.js, app/frontend/containers/MapsContainer.js, app/frontend/containers/NoContentsContainer.js, app/frontend/containers/NotificationListContainer.js, app/frontend/containers/NotificationsContainer.js, app/frontend/containers/ProfileContainer.js, app/frontend/containers/TimelineContainer.js, app/frontend/ui/CreateMapButton.jsx, app/frontend/ui/CreateReviewButton.jsx, app/frontend/ui/Discover.jsx, app/frontend/ui/Invites.jsx, app/frontend/ui/MapCollection.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/NoContents.jsx, app/frontend/ui/NotificationList.jsx, app/frontend/ui/Notifications.jsx, app/frontend/ui/Profile.jsx, app/frontend/ui/ReviewDetail.jsx, app/frontend/ui/SpotDetail.jsx, app/frontend/ui/Timeline.jsx
=> Refactor Components

app/frontend/containers/AppContainer.js, app/frontend/containers/CopyReviewDialogContainer.js, app/frontend/containers/CreateMapDialogContainer.js, app/frontend/containers/EditMapDialogContainer.js, app/frontend/containers/EditReviewDialogContainer.js, app/frontend/containers/NavBarContainer.js, app/frontend/ui/App.jsx, app/frontend/ui/Discover.jsx, app/frontend/ui/Invites.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/Notifications.jsx, app/frontend/ui/Profile.jsx, app/frontend/ui/ReviewDetail.jsx, app/frontend/ui/ReviewsDialog.jsx, app/frontend/ui/Settings.jsx, app/frontend/ui/SpotDetail.jsx, app/frontend/ui/Timeline.jsx
* レイアウトの修正
* リンクの改善
* 新しいタブで開けるようにしました
=> Grid with app menu

functions/package-lock.json, functions/package.json
=> functions: npm update

app/frontend/containers/BottomNavContainer.js, app/frontend/ui/BottomNav.jsx
react-router の `<Link>` を使って遷移するようにしました。
=> Improve bottom nav

app/frontend/containers/MapSummaryContainer.js, app/frontend/ui/MapSummary.jsx, app/frontend/ui/Profile.jsx
サマリー画面上の小さいマップをタップすると Google マップを開けるようにしました。
=> Render mini google map on summary (mobile)

app/frontend/ui/MapSummary.jsx
モバイル版の Google マップの配置がイケてなかったので直しました。
=> Fix mini map style

app/frontend/ui/MapSummary.jsx
モバイル用マップのレイアウト変更に伴うスタイル崩れを修正しました。
=> Tweak mobile map

app/frontend/containers/CreateReviewButtonContainer.js, app/frontend/containers/SpotDetailContainer.js, app/frontend/ui/SpotDetail.jsx
スポット詳細画面上のレポート作成ボタンについて、共通部品を使うようにしました。
=> Refactoring: create review button

app/frontend/containers/AppContainer.js, app/frontend/containers/LocationButtonContainer.js, app/frontend/containers/PlaceSelectDialogContainer.js, app/frontend/ui/App.jsx, app/frontend/ui/Discover.jsx, app/frontend/ui/LocationButton.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/PlaceSelectDialog.jsx
1. 現在地取得ボタンを追加しました。
また、現在地取得のタイミングを「アプリ起動時」から「現在地ボタンを押した際」 および「プレイス選択ダイアログを開いた際」に変更しました。
2. Discover 画面のレイアウトを変更しました。
=> Location button

app/frontend/ui/App.jsx, app/frontend/ui/Invites.jsx, app/frontend/ui/MapCollection.jsx, app/frontend/ui/Notifications.jsx, app/frontend/ui/Profile.jsx, app/frontend/ui/ReviewDetail.jsx, app/frontend/ui/Settings.jsx, app/frontend/ui/SpotDetail.jsx, app/frontend/ui/Timeline.jsx
レイアウトを改善しました。
また、マップのサムネイル画像についてモバイルでは圧縮した画像を表示するようにしました。
=> Fix grid layout

app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/Profile.jsx
=> Tweak styles

app/frontend/ui/MapCollection.jsx, app/frontend/ui/MapSummary.jsx
=> Update map tile style

app/frontend/ui/MapCollection.jsx
=> Fix follow check

app/frontend/containers/AppContainer.js, app/frontend/containers/RequestNotificationDialogContainer.js, app/frontend/ui/RequestNotificationDialog.jsx
プッシュ通知許可リクエストまわりを修正しました。
* プッシュ通知に対応してないブラウザでは許可リクエストダイアログを表示しないようにしました。
* アプリ起動時に毎回登録トークンをサーバに送信するのではなく、トークンが更新されたタイミングで随時送信するようにしました。
* 許可リクエストダイアログの style を微修正しました。
=> Fix push notification request

package.json, yarn.lock
firebase-tools をあらかじめ docker container 内にインストールしておくようにし、ローカル端末へのインストールを不要としました。
=> Install firebase in docker container

Dockerfile, package.json
npm scripts と Dockerfile を微修正。
=> Fix setup scripts

app/functions/index.js
firebase functions のリージョンを asia-northeast1 に変更しました。
=> Fix firebase functions region

app/frontend/containers/ProfileContainer.js, app/frontend/ui/Profile.jsx
匿名ユーザーの場合はプロフィール編集ダイアログを開けないようにしました。
=> Update profile requires sign in

app/frontend/ui/Profile.jsx, app/functions/Utils.js
google bot は JS をちゃんと実行できているようなので bot 用のルートではなく通常のユーザーと同じルートに流すようにしました。
=> Normal route for google bot

app/frontend/containers/NotificationsContainer.js, app/frontend/ui/EditMapDialog.jsx, app/functions/index.js, functions/package.json, functions/yarn.lock
feedback を受け取ったら某 slack に通知されるようにしました。
=> Add feedback hook

app/frontend/containers/EditReviewDialogContainer.js, app/frontend/containers/I18n.js, app/frontend/locales/en.json, app/frontend/ui/App.jsx, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/Privacy.jsx, app/frontend/ui/Terms.jsx, app/views/index.html
* マップ新規作成の導線がわかりづらかったのでレビュー作成ダイアログにボタンを設置しました。
* iOS で日本語文言が表示されない問題を修正しました。
=> Create map button on review form

functions/hosting/robots.txt, functions/hosting/sitemap.xml
=> Add sitemap.xml

app/frontend/containers/LoginContainer.js, app/frontend/containers/PrivacyContainer.js, app/frontend/containers/TermsContainer.js, app/frontend/ui/App.jsx, app/frontend/ui/Login.jsx, app/frontend/ui/NavBar.jsx, app/frontend/ui/Privacy.jsx, app/frontend/ui/Terms.jsx
* ログイン画面などで Appbar を重複してレンダリングしていた問題を修正しました。
* ログイン画面や利用規約のページでは Bottom Nav を表示しないようにしました。
=> Fix duplicate nav

.gitignore, app/frontend/containers/NavBarContainer.js, app/frontend/ui/NavBar.jsx
* Material-UI の component に react-router の Link を指定する形に修正しました。
* モバイル画面ではページタイトルを中央に表示するようにしました。
=> Fix react router link

app/frontend/containers/DiscoverContainer.js, app/frontend/containers/LikesDialogContainer.js, app/frontend/containers/MapCollectionContainer.js, app/frontend/containers/MapSummaryContainer.js, app/frontend/containers/NotificationListContainer.js, app/frontend/containers/ReviewCardContainer.js, app/frontend/ui/BottomNav.jsx, app/frontend/ui/Discover.jsx, app/frontend/ui/LikesDialog.jsx, app/frontend/ui/MapCollection.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/NotificationList.jsx, app/frontend/ui/ReviewCard.jsx
react-router の Link コンポーネントの使い方を見直しました。
=> Refactor links

app/frontend/ui/Profile.jsx, package.json, yarn.lock
画像の高さが微妙に考慮されていないのでタイルレイアウトは一旦諦めます。
=> Remove react-stack-grid

app/frontend/ui/Profile.jsx
=> Tweak styles on profile

app/frontend/ui/Discover.jsx
=> Fixed problem that discover page can not be loaded

app/frontend/containers/DeleteReviewDialogContainer.js, app/frontend/containers/EditReviewDialogContainer.js, app/frontend/containers/ReviewCardContainer.js, app/frontend/containers/ReviewDialogContainer.js, app/frontend/reducers/mapSummaryReducer.js, app/frontend/ui/Discover.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewDetail.jsx, app/frontend/ui/ReviewGridList.jsx
Review API のデータ構造を変えたことに伴う修正です。
=> Fix review json

app/frontend/ui/App.jsx, app/frontend/ui/Discover.jsx, app/frontend/ui/Maps.jsx, app/frontend/ui/Profile.jsx, app/frontend/ui/Routes.jsx, app/frontend/ui/SharedDialogs.jsx
=> Refactor routes

.dockerignore, Dockerfile, functions/package.json, package.json, yarn.lock
CI/CD 周りの自動化に向けて、Docker イメージをもろもろ更新しました。
=> Update docker image for GCP

app/frontend/containers/AppContainer.js, app/frontend/ui/App.jsx
=> Fix app initialization

.dockerignore, Dockerfile
functions ディレクトリで yarn install するのを忘れていました。
=> yarn install for functions in Dockerfile

app/functions/index.js, package.json, yarn.lock
firebase の機能を使って環境変数をセットするようにしました。
https://firebase.google.com/docs/functions/config-env?hl=ja
=> Use functions:config

app/functions/index.js, cloudbuild.yaml, functions/package.json, functions/yarn.lock
Cloud Build (Pub/Sub) のイベントを subscribe して slack に通知する関数を追加しました。
=> Subscribe events from Cloud Build

app/functions/index.js
=> Remove undefined param from functions

.babelrc, .gitignore, app/frontend/index.js, app/frontend/ui/App.jsx, app/frontend/ui/Routes.jsx, app/frontend/ui/SharedDialogs.jsx, package.json, webpack.config.js, yarn.lock
bundle size がでかすぎるので code splitting しました。
https://webpack.js.org/guides/code-splitting/
https://reactjs.org/docs/code-splitting.html
https://github.com/smooth-code/loadable-components
=> Route-based code splitting with loadable-components

app/frontend/containers/ApiClient.js, app/frontend/containers/AppContainer.js, app/frontend/containers/EditReviewDialogContainer.js, app/frontend/containers/NavBarContainer.js, app/frontend/containers/Utils.js, app/frontend/reducers/appReducer.js, app/frontend/ui/App.jsx, app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/NavBar.jsx
First meaningful paint 的なあれでロード画面をなくしました。
https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/
=> Remove loading page

app/frontend/containers/CopyReviewDialogContainer.js, app/frontend/containers/CurrentPositionMarkerContainer.js, app/frontend/containers/LoginButtonsContainer.js, app/frontend/locales/en.json, app/frontend/locales/ja.json, app/frontend/ui/CopyReviewDialog.jsx, app/frontend/ui/CurrentPositionMarker.jsx, app/frontend/ui/MapSummary.jsx, app/frontend/ui/SpotMarkers.jsx
* ログイン時に最新のプロフィール画像が表示されない問題を修正しました。
* マップサマリーから FB/Twitter のシェアボタンを削除しました (アクション一覧のシェアボタンはこれまで通り維持)。
* レポートをコピーする際に、コピー先のマップ一覧が取得されない問題を修正しました。
* 現在地に自分のプロフィールアイコンが表示されるようにしました。
=> Update current position marker

app/functions/QoodishClient.js, app/functions/Utils.js, app/functions/index.js
* Cloud Functions 上で環境変数を参照できていない箇所があったので修正しました。
* レビュー画像のサムネイルを作成する関数を asia-northeast1 に移しました。
=> Fix functions env variables

functions/hosting/sw.js
=> Recover sw.js

app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/Routes.jsx, package.json, yarn.lock
dynamic imports で JS ファイルがロードされない問題を修正しました (webpack のバージョンを上げました)。
=> Fix dynamic import issue

package.json, yarn.lock
Material-UI を v3.3.2 にアップグレードしました。
=> Upgrade Material-UI to v3.3.2

app/frontend/containers/AppContainer.js, app/frontend/containers/BottomNavContainer.js, app/frontend/containers/NavBarContainer.js, app/frontend/reducers/sharedReducer.js, app/frontend/ui/App.jsx, app/frontend/ui/Login.jsx, app/frontend/ui/NavBar.jsx
router 周りの状態管理を reducer に移譲 + 軽微なバグを修正。
=> Refactoring: React components

app/frontend/containers/ProfileContainer.js, app/frontend/containers/UserProfileContainer.js
react-router-redux の残骸が残っていました。
=> Fix router bug

app/frontend/ui/Privacy.jsx, app/frontend/ui/Terms.jsx, app/functions/QoodishClient.js, app/functions/Utils.js
bot がスポットの URL にアクセスした際に metadata が展開されるようにしました。
=> Fetch spot metadata for bot

app/frontend/ui/ReviewDialog.jsx
review dialog のスクロールを改善しました (PC サイズ)。
=> Scroll review dialog body

app/frontend/ui/Discover.jsx
=> Tweak layout of discover

app/frontend/ui/RecentReviews.js
最近投稿されたレポートについて、モバイル端末では水平スクロールで表示するようにしました。
=> Recent reviews with horizontal scroll

app/frontend/ui/SearchBar.jsx
マップ検索結果の List のスタイルを微修正しました。
* タブキーで検索結果を選択できるようにしました。
=> Tweak styles of search results

package.json, yarn.lock
Webpack v4.26.0 に上げました。
https://github.com/webpack/webpack/releases
=> Webpack v4.26.0

app/frontend/ui/SearchMapsDialog.jsx
=> Tweak search dialog

app/frontend/ui/SearchMapsDialog.jsx
=> Fix search dialog style

app/views/index.html
react-helmet による title タグの動的更新が機能していなかったようなので修正。
=> Fix SEO issue

app/frontend/ui/EditReviewDialog.jsx, package.json, yarn.lock
スマホで画像をアップロードした際に意図せず画像が回転してしまう問題を修正しました。
=> Fix image exif

app/frontend/ui/EditProfileDialog.jsx
プロフィール画像編集ボタンが表示されなくなっていた問題を修正しました。
=> Fix style of edit profile image button

app/frontend/ui/EditReviewDialog.jsx, app/frontend/ui/GMap.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/MapSummary.jsx
マップ詳細画面について code splitting を実施しました。
=> Code splitting: Map Detail

app/frontend/containers/MapDetailContainer.js, app/frontend/ui/MapDetail.jsx
=> Refactoring: Map Detail

app/frontend/containers/MapVertMenuContainer.js, app/frontend/containers/ReviewCardActionsContainer.js, app/frontend/containers/ReviewCardContainer.js, app/frontend/containers/ReviewShareMenuContainer.js, app/frontend/containers/ReviewVertMenuContainer.js, app/frontend/locales/en.json, app/frontend/locales/ja.json, app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewCardActions.jsx, app/frontend/ui/ReviewShareMenu.jsx, app/frontend/ui/ReviewVertMenu.jsx
=> Split components of Review Card

app/frontend/ui/ReviewComments.jsx
コメント上のプロフィールアイコンをタップすると、ユーザープロフィールページに遷移するようにしました。
=> Add user link on comment

app/frontend/ui/ReviewCard.jsx, app/frontend/ui/ReviewComments.jsx, app/frontend/ui/ReviewDialog.jsx
Review Dialog 上でコメントを投稿 (更新) した際に、画面上で即時反映されない問題を修正しました。
=> Fixed an issue that does not take effect immediately when posting comments

app/frontend/reducers/reviewsReducer.js, app/frontend/ui/ReviewCard.jsx
* マップ詳細画面の状態管理を見直し、不要なリフレッシュ処理を削除しました。
* Review Card コンポーネントをリファクタリングしました。
=> Fix state management of Map Detail

app/frontend/containers/SpotImageStepperContainer.js, app/frontend/ui/SpotCard.jsx, app/frontend/ui/SpotImageStepper.jsx
Spot Card 上の画像を stepper で切り替えられるようにしました。
=> Add stepper on spot card

app/frontend/ui/NotificationList.jsx, app/frontend/ui/NotificationMenu.jsx, app/frontend/ui/ReviewCard.jsx
Notification まわりの style を微調整しました。
=> Tweak styles of notifications

app/frontend/actions/openLeaveMapDialog.js, app/frontend/containers/FollowMapButtonContainer.js, app/frontend/containers/LeaveMapDialogContainer.js, app/frontend/reducers/mapDetailReducer.js, app/frontend/reducers/mapsReducer.js, app/frontend/reducers/profileReducer.js, app/frontend/ui/LeaveMapDialog.jsx, app/frontend/ui/MapDetail.jsx, app/frontend/ui/SharedDialogs.jsx
=> Unfollowing map from following maps dialog

app/frontend/containers/MapToolbarContainer.js, app/frontend/containers/MapVertMenuContainer.js, app/frontend/ui/EditMapDialog.jsx, app/frontend/ui/MapToolbar.jsx, app/frontend/ui/MapVertMenu.jsx
* 招待ボタンを編集/削除ボタンと同じメニューの中に移動しました。
* その他 style 微調整。
=> Tweak layout of map toolbar

app/frontend/ui/ReviewGridList.jsx, app/frontend/ui/ReviewTiles.jsx
レポート一覧で画像がないときに表示される代替画像について、マテリアルアイコンを表示するように変更しました。
=> Use place icon for substitute image

functions/generateThumbnail/index.js, functions/index.js, functions/notifyBuilds/index.js, functions/notifyFeedback/index.js
Cloud Functions 周りの処理を複数ファイルに分割しました。
=> Refactoring: cloud functions

functions/generateThumbnail/index.js, functions/package.json, functions/yarn.lock
Cloud Functions が使用しているライブラリのバージョンを上げました。
=> Upgrade dependencies for cloud functions

src/frontend/components/molecules/ReviewLikeActions.js, src/frontend/components/organisms/LoginButtons.js, src/frontend/components/pages/MapDetail.js
=> Bug: ownProps to props

src/frontend/components/molecules/ProfileAvatar.js, src/frontend/components/organisms/ProfileReviews.js, src/frontend/components/organisms/SharedProfile.js, src/frontend/reducers/profileReducer.js
自分以外のユーザーのプロフィールが正常に参照できない問題を修正しました。
=> Fix bugs on profile page

src/frontend/components/organisms/NotificationList.js, src/frontend/components/organisms/ProfileReviews.js, src/frontend/components/organisms/RecentReviews.js, src/frontend/components/organisms/TrendingMaps.js, src/frontend/components/organisms/TrendingSpots.js, src/frontend/components/pages/Discover.js, src/frontend/components/pages/Invites.js, src/frontend/components/pages/Notifications.js, src/frontend/components/pages/ReviewDetail.js, src/frontend/components/pages/SpotDetail.js, src/frontend/components/pages/Timeline.js
=> Tweak loading states

src/frontend/components/organisms/ProfileReviews.js, src/frontend/components/pages/Invites.js, src/frontend/components/pages/Notifications.js, src/frontend/components/pages/Timeline.js
匿名ユーザーでログインしていた場合に、各画面が loading 状態のままになってしまう問題を修正しました。
=> Fix loading states for anonymous user

src/frontend/components/Routes.js, src/frontend/components/molecules/MapToolbar.js, src/frontend/components/organisms/MapBottomSeat.js, src/frontend/components/organisms/MapSummary.js, src/frontend/components/pages/MapDetail.js
マップサマリーをブラウザの「戻る」「進む」ボタンで開閉できるようにしました。
=> Push history on open Map Summary

src/frontend/reducers/reviewsReducer.js
ダイアログで開いたレビューに対して更新やコメント投稿をした際に、即座に反映されない問題を修正しました。
=> Reflect update on review dialog

src/frontend/components/molecules/CommentMenu.js, src/frontend/components/molecules/ReviewCard.js, src/frontend/components/molecules/ReviewCardActions.js, src/frontend/components/molecules/ReviewComments.js, src/frontend/components/molecules/SharedLikeActions.js, src/frontend/components/organisms/ReviewDialog.js, src/frontend/components/organisms/TrendingMaps.js, src/frontend/components/pages/Timeline.js, src/frontend/locales/en.json, src/frontend/locales/ja.json
=> Update like comment button

src/frontend/components/Routes.js, src/frontend/components/pages/MapDetail.js, src/frontend/reducers/sharedReducer.js
=> Fix back button not working

src/frontend/components/pages/MapDetail.js
ダイアログを開いた際に、意図せずマップ詳細画面がリロードされてしまう問題を修正しました。
=> Fix effect of refreshing map

src/frontend/components/organisms/SpotCard.js
=> Fix opening hours

functions/notifyBuilds/index.js
Cloud Build のビルド結果をより詳細に Slack に通知するように修正しました。
=> Update slack notifier

functions/notifyBuilds/index.js
=> Tweak slack message

src/frontend/components/App.js
=> Fix initialization of FCM

package.json, src/frontend/components/App.js, src/frontend/components/molecules/SearchBar.js, src/frontend/components/organisms/CopyReviewDialog.js, src/frontend/components/organisms/CreateMapDialog.js, src/frontend/components/organisms/DeleteMapDialog.js, src/frontend/components/organisms/EditMapDialog.js, src/frontend/components/organisms/EditReviewDialog.js, src/frontend/components/organisms/SearchMapsDialog.js, src/frontend/components/organisms/SharedEditMapDialog.js, src/frontend/components/organisms/TrendingMaps.js, src/frontend/components/pages/Discover.js, src/frontend/components/pages/Invites.js, src/frontend/components/pages/Notifications.js, src/frontend/components/pages/ReviewDetail.js, src/frontend/components/pages/Timeline.js, src/frontend/utils/ApiClient.js, src/frontend/utils/initializeApiClient.js, yarn.lock
Qoodish API Client を openapi-generator で作成しました。
https://github.com/yusuke-suzuki/qoodish-api-js-client
=> New Qoodish API client

package.json, src/frontend/components/App.js, src/frontend/components/organisms/DeleteAccountDialog.js, src/frontend/components/organisms/EditProfileDialog.js, src/frontend/components/organisms/InviteTargetDialog.js, src/frontend/components/organisms/LoginButtons.js, src/frontend/components/organisms/PickUpMap.js, src/frontend/components/organisms/ProfileMyMaps.js, src/frontend/components/pages/MapDetail.js, src/frontend/components/pages/Profile.js, src/frontend/components/pages/Settings.js, src/frontend/components/pages/UserProfile.js, src/frontend/utils/ApiClient.js, yarn.lock
Users API について新しい API client を使用するようにしました。
=> Update API client

src/frontend/components/App.js, src/frontend/components/molecules/AvatarMenu.js
firebase user  の初期化プロセスを見直しました。
=> Tweak authentication

package.json, src/frontend/components/Layout.js, src/frontend/components/organisms/RecommendMaps.js, src/frontend/locales/en.json, src/frontend/locales/ja.json, yarn.lock
画面右側のエリアにおすすめのマップを表示するようにしました。
=> Show recommend maps

src/frontend/components/Layout.js
ログインページなどでおすすめのマップ一覧が非表示になるように修正しました。
=> Hide recommend maps on login page and other

src/frontend/components/molecules/AppMenuButton.js, src/frontend/components/molecules/DialogAppBar.js, src/frontend/components/molecules/MapToolbar.js, src/frontend/components/molecules/NavDrawer.js, src/frontend/components/molecules/ProfileAvatar.js, src/frontend/components/molecules/ProfileCard.js, src/frontend/components/organisms/NavToolbar.js, src/frontend/components/organisms/SearchMapsDialog.js, src/frontend/components/organisms/SharedProfile.js
メニュー (Drawer) 上部 にプロフィールを表示するようにしました。
=> Profile on drawer

src/frontend/components/molecules/AppMenuButton.js, src/frontend/components/molecules/ProfileAvatar.js, src/frontend/components/molecules/ProfileCard.js, src/frontend/components/organisms/FollowingMapsDialog.js, src/frontend/components/organisms/LikesDialog.js, src/frontend/components/organisms/NavToolbar.js, src/frontend/components/organisms/SharedProfile.js
* 他のユーザーのプロフィール画面なのに自分のアイコンが表示されてしまう問題を修正しました。
* 一部ダイアログで toolbar が固定されずにスクロールされてしまう問題を修正しました。
* モバイルにおいて、navbar にページタイトルではなくアプリ名 (Qoodish) を出すようにしました。
* その他 style を微修正しました。
=> Fix profile avatar

package.json, src/frontend/components/molecules/DialogAppBar.js, src/frontend/components/molecules/FollowMapButton.js, src/frontend/components/molecules/MapLikeActions.js, src/frontend/components/molecules/MapToolbar.js, src/frontend/components/molecules/MapVertMenu.js, src/frontend/components/molecules/ReactionsCount.js, src/frontend/components/molecules/ReviewCard.js, src/frontend/components/molecules/ReviewComments.js, src/frontend/components/molecules/ReviewLikeActions.js, src/frontend/components/molecules/SharedLikeActions.js, src/frontend/components/organisms/MapBottomSeat.js, src/frontend/components/organisms/MapCollection.js, src/frontend/components/organisms/MapSummary.js, src/frontend/components/organisms/MapSummaryCard.js, src/frontend/components/organisms/NavToolbar.js, src/frontend/components/organisms/ProfileMyMaps.js, src/frontend/components/organisms/ProfileReviews.js, src/frontend/locales/en.json, src/frontend/locales/ja.json, yarn.lock
=> Display comment likes

functions/hosting/sw.js, src/frontend/components/App.js, src/frontend/index.js, src/frontend/utils/initializeFirebaseApp.js, src/service_workers/firebase-messaging-sw.js
アプリがフォアグラウンドで起動している際にもプッシュ通知のカードを表示するようにしました。
=> Display notification card in the foreground

src/frontend/components/App.js, src/frontend/components/organisms/PushSettings.js
プッシュ通知購読中/停止中の判定に不必要なパラメータ・処理を削除しました。
=> Remove unnecessary flag for push notification

src/frontend/components/organisms/MapSpotCard.js, src/frontend/reducers/spotCardReducer.js
モバイルでスポットカードが開けなくなっていた問題を修正しました。
=> Fix spot bottom card

src/frontend/components/molecules/SpotImageStepper.js, src/frontend/components/molecules/SpotInfoWindow.js, src/frontend/components/organisms/GMap.js, src/frontend/components/organisms/MapSpotDrawer.js, src/frontend/components/pages/MapDetail.js
PC 版でスポットマーカーをクリックした際に、drawer ではなく popover を開いてスポット詳細を表示するようにしました。
=> Spot info window for PC

package.json, src/frontend/components/molecules/ReviewCardActions.js, src/frontend/components/organisms/NavTabs.js, src/frontend/components/organisms/NotificationList.js, src/frontend/reducers/timelineReducer.js, src/frontend/utils/createRegistrationToken.js, yarn.lock
=> Update devices API

src/frontend/components/molecules/SpotInfoWindow.js, src/frontend/components/organisms/MapSpotDrawer.js
【PC】Spot info window 上にレポート投稿ボタンを設置しました。
* マップの共同編集が ON の場合のみ表示
* すでに対象のスポットについてのレポートを投稿済みの場合は disabled
=> Post review button on spot info window

src/frontend/components/molecules/MapToolbar.js, src/frontend/components/organisms/GMap.js, src/frontend/components/organisms/SpotHorizontalList.js
=> Tweak map detail UI

src/frontend/components/molecules/Logo.js, src/frontend/components/molecules/NavDrawer.js, src/frontend/components/organisms/NavToolbar.js, src/frontend/components/pages/MapDetail.js, src/service_workers/sw.js, src/views/index.html
=> Logo google fonts

src/frontend/components/pages/Timeline.js
ログインユーザーのタイムラインが取得できない問題を修正しました。
=> Fix refresh timeline

src/frontend/components/App.js
ログイン後に画面をリロードすると認証状態が初期化されてしまう問題を修正しました。
=> Fix current user disappeared

src/frontend/components/organisms/SharedPlaceSelectDialog.js, src/frontend/locales/en.json, src/frontend/locales/ja.json
PC 版のプレイス選択ダイアログで、プレイス名を入力するたびにダイアログの高さがガクガク変わってしまう問題を修正しました。
=> Fix height of place select dialog

src/frontend/components/pages/MapDetail.js
タイミングによって、マップ詳細ページが正しく初期化されない問題を修正しました (マップの拠点移動等)。
=> Fix init map detail

src/frontend/components/organisms/SpotHorizontalList.js
Spot Tile (モバイル版) にレポート数を表示するようにしました。
また、style を微調整しました。
=> Tweak spot tiles

cloudbuild.yaml
デプロイ先の firebase プロジェクトを環境変数で切り替えられるようにしました。
=> Add environment variables on cloud build

cloudbuild.yaml, functions/server/index.js
cloud function で metadata が取得されなくなっていたので修正しました。
=> Fix fetch metadata for bots

functions/server/metadata.html
title タグの内容が "Qoodish" で固定になっていたところを、動的に設定できるようにしました。
=> Dynamic rendering title for bots

src/frontend/components/molecules/MapToolbar.js, src/frontend/components/molecules/ReviewCard.js, src/frontend/components/organisms/EditReviewDialog.js, src/frontend/components/organisms/MapSummaryCard.js, src/frontend/components/organisms/SharedEditMapDialog.js, src/frontend/components/pages/MapDetail.js, src/frontend/locales/en.json, src/frontend/locales/ja.json
* Map Summary を開くボタンをツールバー → 地図上に移動しました。
* 各フォーム上における textbox のデフォルトの行数を増やしました。
* マップの説明およびレポートのコメントについて、改行コードが反映されるようにしました。
=> Tweak map toolbar

src/frontend/components/organisms/NavToolbar.js
=> Remove console log

src/frontend/components/molecules/MapToolbar.js
https://github.com/yusuke-suzuki/qoodish-web/pull/408 の問題の修正漏れに対応しました。
=> Fix browser back

functions/server/metadata.html
Google 検索結果にサムネイルが表示されるように、meta thumbnail タグを追加しました。
=> Add meta thumbnail tag

functions/server/index.js
=> Tweak express server

functions/server/index.js
アクセスログに User-Agent が出力されるようにしました。
=> Fix log format

functions/server/utils/isBot.js
note.mu で URL を貼った際にメタデータが展開されるよう、notebot を bot list に加えました。
=> Add notebot to bot list

src/frontend/components/organisms/EditReviewDialog.js
=> Review limit to 500

index.js, src/frontend/components/organisms/EditReviewDialog.js
Rendertron へのリクエスト時に mobile=true を付与するようにしました。
https://github.com/GoogleChrome/rendertron#render
=> Set mobile=true for rendertron

src/frontend/components/App.js, src/frontend/components/molecules/ReactionsCount.js, src/frontend/components/molecules/ReviewCard.js, src/frontend/components/molecules/SearchBar.js, src/frontend/components/organisms/EditReviewDialog.js, src/frontend/components/organisms/FollowingMapsDialog.js, src/frontend/components/organisms/GMap.js, src/frontend/components/organisms/MapSpotDrawer.js, src/frontend/components/organisms/SearchMapsDialog.js, src/frontend/components/organisms/SharedEditMapDialog.js, src/frontend/components/organisms/TrendingMaps.js, src/frontend/components/organisms/TrendingSpots.js
* アプリを開いた状態で 1 時間経過すると `Authentication failed` というエラーが表示され、API からデータが取得できなくなる問題を修正しました。
* その他 UI を微調整しました。
=> Tweak UI/UX

src/frontend/components/AppHelmet.js, src/frontend/components/organisms/SharedPlaceSelectDialog.js, src/frontend/index.js, src/frontend/locales/en.json, src/frontend/locales/ja.json, src/frontend/reducers/metadataReducer.js, src/frontend/utils/detectCurrentLocale.js, src/views/index.html
メタデータを多言語化しました。
https://support.google.com/webmasters/answer/189077?hl=ja
=> Localized meta data

cloudbuild.deploy.yaml
Cloud Build で公式の node イメージを使用するように変更。
=> yarn build with official node image v13.3.0

.gitignore, .npmrc, cloudbuild.deploy.yaml
GPR 上のパッケージを yarn install しようとして 401 エラーになる問題を修正しました。
=> Install packages from GPR with NPM_TOKEN

.npmrc, package.json, src/frontend/components/organisms/SpotDialog.js, yarn.lock
* Install qoodish-api-js-client from npm
* Fix spot dialog
=> Qoodish client from npm

index.js, src/frontend/components/organisms/CopyReviewDialog.js, src/frontend/components/organisms/PushSettings.js, src/frontend/components/organisms/SharedEditMapDialog.js, src/frontend/components/pages/ReviewDetail.js
* レビュー詳細画面において、別のレビューの詳細表示に切り替えられない問題を修正しました
* プッシュ通知設定が初回ロード時に正しく反映されない問題を修正しました
* マップ編集ダイアログについて、UI を微修正しました
* マップ編集ダイアログについて、マップ名の最大文字数のバリデーションが正しく機能しない問題を修正しました
* JS ファイルのキャッシュ有効期間を 1 ヶ月 → 6 ヶ月に延長しました
* レポートコピーダイアログの UI を微調整しました
=> Fix UI bugs

src/frontend/reducers/sharedReducer.js
ページ遷移数のカウントロジックが間違っていたので修正しました。
=> Fixed counting history

src/frontend/components/molecules/MapCard.js, src/frontend/components/molecules/ProfileAvatar.js, src/frontend/components/molecules/ReviewCard.js, src/frontend/components/molecules/SpotImageStepper.js, src/frontend/components/organisms/MapSpotDrawer.js, src/frontend/components/organisms/PickUpMap.js, src/frontend/components/organisms/RecentReviews.js, src/frontend/components/organisms/ReviewDialog.js, src/frontend/components/organisms/ReviewGridList.js, src/frontend/components/organisms/ReviewTiles.js, src/frontend/components/organisms/SpotHorizontalList.js, src/frontend/utils/canvasToBlob.js
400x400, 800x800 サイズのサムネイルに対応しました。
=> Use multiple resized images

src/frontend/components/organisms/EditProfileDialog.js, src/frontend/components/organisms/EditReviewDialog.js, src/frontend/components/organisms/LoginButtons.js, src/frontend/components/pages/MapDetail.js, src/frontend/components/pages/ReviewDetail.js, src/frontend/components/pages/SpotDetail.js
=> Render metadata with thumbnails

src/frontend/components/molecules/ReviewCard.js, src/frontend/components/molecules/SpotMarker.js, src/frontend/components/organisms/ReviewDialog.js, src/frontend/components/organisms/TrendingSpots.js
オリジナルサイズの画像を表示してしまっている箇所をサムネイルに差し替えました。
=> Fix thumbnails

webpack.config.js
=> Add hash for index.html

index.js, package.json, yarn.lock
=> Apply long cache TTL for static files (1 year)

src/frontend/components/molecules/MapCard.js, src/frontend/components/molecules/ProfileAvatar.js, src/frontend/components/molecules/ReviewCard.js, src/frontend/components/molecules/ReviewComments.js, src/frontend/components/molecules/SpotImageStepper.js, src/frontend/components/molecules/SpotInfoWindow.js, src/frontend/components/molecules/SpotMarker.js, src/frontend/components/organisms/CopyReviewDialog.js, src/frontend/components/organisms/FollowingMapsDialog.js, src/frontend/components/organisms/LikesList.js, src/frontend/components/organisms/MapReviewsList.js, src/frontend/components/organisms/MapSpotDrawer.js, src/frontend/components/organisms/MapSummaryCard.js, src/frontend/components/organisms/NotificationList.js, src/frontend/components/organisms/PickUpMap.js, src/frontend/components/organisms/RecentReviews.js, src/frontend/components/organisms/ReviewGridList.js, src/frontend/components/organisms/ReviewTiles.js, src/frontend/components/organisms/SharedProfile.js, src/frontend/components/organisms/SpotCard.js, src/frontend/components/organisms/SpotHorizontalList.js, src/frontend/components/organisms/TrendingMaps.js, src/frontend/components/organisms/TrendingSpots.js
=> Lazy loading images

package.json, src/components/molecules/MapSelect.js, src/components/molecules/ReviewCard.js, src/components/molecules/ReviewCommentForm.js, src/components/molecules/ReviewImagePreview.js, src/components/molecules/ReviewImageStepper.js, src/components/molecules/ReviewVertMenu.js, src/components/molecules/SaveReviewButton.js, src/components/molecules/SpotImageStepper.js, src/components/organisms/EditReviewDialog.js, src/components/organisms/MapReviewsList.js, src/components/organisms/MapSpotDrawer.js, src/components/organisms/RecentReviews.js, src/components/organisms/ReviewImageTile.js, src/components/pages/Timeline.js, src/utils/uploadToStorage.js, yarn.lock
* レポートに複数の画像を付けられるようにしました
* レポートコピー機能を一旦無効化しました
=> Multiple Review images

src/components/organisms/EditReviewDialog.js
画像ファイル選択時に、同時に複数のファイルを選択できるように修正。
=> Add images with multiple files

src/components/molecules/MapSelect.js
レポート編集時に、マップの初期状態が「投稿可能なマップの 1 件目」になってしまう問題を修正しました。
=> Fix map select

src/components/organisms/EditProfileDialog.js, src/components/organisms/EditReviewDialog.js, src/components/organisms/FeedbackDialog.js, src/components/organisms/FollowingMapsDialog.js, src/components/organisms/ImageDialog.js, src/components/organisms/InviteTargetDialog.js, src/components/organisms/LeaveMapDialog.js, src/components/organisms/LikesDialog.js, src/components/organisms/MapGridList.js, src/components/organisms/RecentReviews.js, src/components/organisms/ReviewDialog.js, src/components/organisms/SharedEditMapDialog.js, src/components/organisms/SharedPlaceSelectDialog.js, src/components/organisms/SignInRequiredDialog.js, src/components/organisms/SpotDialog.js, src/components/pages/Discover.js
* Discover ページのレイアウト崩れを修正
* レポート画像追加時の validation で、`file.name` を使用しないように修正
* iOS でサポートされていなかった
* https://developer.mozilla.org/ja/docs/Web/API/File/name
=> Fix grid styles

src/components/pages/ReviewDetail.js
レポートの OGP 画像が正しく設定されなくなっていたので修正しました。
=> Fix review ogp image

src/components/organisms/ProfileMyMaps.js, src/components/organisms/SharedProfile.js, src/components/pages/ReviewDetail.js, src/reducers/reviewDetailReducer.js
* レポート詳細画面 → マップ → 戻る → レポート詳細画面 と遷移したときに、レポートが表示されなくなる問題を修正
* プローフィール画面 → マップ一覧のレイアウト崩れを修正
=> Fix review details

src/components/organisms/EditReviewDialog.js
レポート編集ダイアログに既存画像のプレビューが表示されない問題を修正
=> Fix initialize image previews on edit review

Dockerfile, cloudbuild.deploy.yaml
Update node image to `13.10.1-alpine3.11`.
=> Node v13.10.1

cloudbuild.deploy.yaml
=> Set secrets version

cloudbuild.deploy.yaml, src/components/molecules/QoodishAssets.js, src/components/molecules/ReviewImageStepper.js, src/components/organisms/MapSummaryCard.js, src/components/organisms/NavBar.js, src/components/organisms/ReviewImageTile.js, webpack.config.js
=> Fix map details bugs

package.json, src/components/organisms/CreateMapDialog.js, src/components/organisms/EditMapDialog.js, src/components/organisms/EditProfileDialog.js, src/components/organisms/SharedEditMapDialog.js, yarn.lock
Support updating map thumbnails.
=> Support updating map thumbnails

src/components/molecules/CreateResourceButton.js, src/components/organisms/SharedEditMapDialog.js, src/components/pages/MapDetail.js
Open place select dialog on map details
=> Open place select dialog on map details

src/components/organisms/LoginButtons.js, src/components/pages/Login.js
Redirect after login only if nextPath is specified.
=> Fix login flow

src/components/molecules/SpotInfoWindow.js, src/components/organisms/CopyReviewDialog.js, src/reducers/reviewsReducer.js, src/reducers/spotCardReducer.js
=> Get Place ID from spots

src/components/organisms/EditReviewDialog.tsx
Fixed to display the current review images on Edit Review Dialog.
=> Fix edit review dialog

src/components/molecules/OverlayView.tsx, src/components/organisms/GMap.tsx
=> Fix spot info window

src/GoogleMapsContext.ts, src/components/molecules/CurrentPositionIcon.tsx, src/components/molecules/CurrentPositionMarker.tsx, src/components/molecules/OverlayView.tsx, src/components/molecules/SpotInfoWindow.tsx, src/components/molecules/SpotMarker.tsx, src/components/organisms/GMap.tsx, src/components/organisms/SpotMarkers.tsx
https://developers.google.com/maps/documentation/javascript/reference/overlay-view
https://developers.google.com/maps/documentation/javascript/customoverlays
=> Improve Google Maps

src/components/organisms/MapSpotDrawer.tsx
=> Tweak map spot drawer

tsconfig.json
- Add `"moduleResolution": "node"` on tsconfig.json
- Remove `"include": ["node_modules/**/*.d.ts"]`from tsconfig.json
=> tsconfig: Specify moduleResolution as node

Dockerfile, cloudbuild.deploy.yaml, entrypoint.sh, webpack.config.js
* Fix Dockerfile for Cloud Run
* Using Berglas
=> Deploy to Cloud Run

.github/workflows/prod.yaml
=> Fix prod workflow

scripts/deleteAnonymousUsers.js, src/components/molecules/AppMenuButton.tsx, src/components/molecules/BackButton.tsx, src/components/molecules/MapToolbar.tsx, src/components/molecules/NavDrawer.tsx, src/components/molecules/ProfileAvatar.tsx, src/components/molecules/ReviewCard.tsx, src/components/molecules/ReviewCardActions.tsx, src/components/molecules/SearchButton.tsx, src/components/molecules/SharedLikeActions.tsx, src/components/organisms/NavToolbar.tsx, src/components/organisms/ReviewDialog.tsx, src/components/organisms/SharedProfile.tsx, src/components/organisms/SignInRequiredDialog.tsx, src/hooks/usePushManager.ts, src/pages/profile/index.tsx, src/reducers/appReducer.ts, src/reducers/profileReducer.ts
- Add script: deleteAnonymousUsers
- Fix anonymous user state
- Tweak layout
=> Fix anonymous state

src/pages/maps/[mapId]/index.tsx, src/pages/maps/[mapId]/reports/[reviewId].tsx
=> Fix page metadata

src/components/molecules/ReviewLink.tsx, src/components/molecules/SpotLink.tsx
=> Tweak spot and review URL

src/components/molecules/ReviewLink.tsx, src/components/molecules/SpotLink.tsx
=> Tweak review and spot URL

next.config.js, package.json, pnpm-lock.yaml, src/components/AuthProvider.tsx, src/components/Layout.tsx, src/components/layouts/LoginCard.tsx, src/components/layouts/MobileDrawer.tsx, src/components/layouts/SignInRequiredDialog.tsx, src/components/layouts/SignInWithGoogleButton.tsx, src/components/maps/MapMenuButton.tsx, src/components/reviews/ReviewMenuButton.tsx, src/hooks/useDictionary.ts, src/pages/_app.tsx, src/pages/login/index.tsx, src/worker/index.ts, workbox-config.js
- Add workbox-webpack-plugin
- Remove firebaseui
- Improve auth flow
- Fix useDictionary
=> Fix workbox config

src/components/maps/CustomOverlays.tsx, src/components/maps/ReviewPopover.tsx, src/components/reviews/LikeReviewButton.tsx, src/pages/404.tsx, src/pages/maps/[mapId]/index.tsx, src/pages/maps/[mapId]/reports/[reviewId].tsx, src/pages/users/[userId].tsx
- Fix 404 error page routing
- Refresh review popover after updating a review
=> Fix error handling

.github/workflows/dev.yaml, .github/workflows/prod.yaml
https://cloud.google.com/run/docs/configuring/services/cpu#startup-boost
=> Enable CPU Boost

src/pages/maps/[mapId]/index.tsx, src/pages/maps/[mapId]/reports/[reviewId].tsx
- Fixed an issue where a 404 page would be displayed when requesting a private map.
=> Fix 404 page rendering
