yusuke-suzuki/qoodish-web

index.js
package.json

babel-register の指定の仕方を間違っていました。
あと koa.js 側の `import '@babel/polyfill';` もまだ必要でした。

Fix babel-register

---

app/views/index.html

ページをロードした時にページビューを重複してカウントしてしまっていたので修正。

Remove unnecessarry code for Google analytics

---

app/frontend/containers/Utils.js
app/frontend/ui/App.jsx
app/functions/Utils.js

レポートの画像がキャッシュされるように設定しました (とりあえず一日)。
既存の画像については↓で設定。
`gsutil -m setmeta -h "Cache-Control:public, max-age=86400" gs://<バケット>/*`

Set cache-control to review images

---

app/frontend/ui/MapDetail.jsx
app/frontend/ui/SpotDetail.jsx
app/views/index.html
webpack.config.js

Google マップがページのレンダリングをブロックしていたようなので非同期で読み込むようにしました。
https://tomchentw.github.io/react-google-maps/#withscriptjs
https://developers-jp.googleblog.com/2015/10/google-maps-api.html

Load Google Map asynchronously

---

app/frontend/ui/MapBottomSeat.jsx

`position: inherit` が効かない一部のブラウザでマップサマリーを開くボタンが隠れてしまう問題を修正しました。

Fix style of open summary button

---

Dockerfile
package.json

node v10.7.0 だと `firebase serve` が動かないので v8.11.3 に修正しました。

Fix node version to v8.11.3 for firebase functions

---

app/functions/index.js

firebase hosting から Tokyo リージョンに上げた functions にリダイレクトさせたいのに、なぜかいくらやっても US リージョンの functions にリダイレクトしようとして Error になってしまう (Error の前に謎の Google アカウント認証画面が表示される) ため、リージョン指定を断念しました。
function 名はリージョンごとに固有らしいので rename や旧 function の削除等も試したのですがだめでした。
https://firebase.google.com/docs/hosting/functions?hl=ja

Functions: set default region

---

app/frontend/containers/Utils.js
app/frontend/ui/Discover.jsx
app/frontend/ui/LoginButtons.jsx
package.json
yarn.lock

* iOS 端末の場合は popup ではなく redirect でサインインするようにしました。これにより iOS PWA でのサインインができるようになるはず (なんか 2 回ログインボタン押さないといけないっぽい)。
* firebase-ui をアップグレードしました (サインイン時の挙動が若干改善されました)。

Use redirect as sign in flow on iOS

---

app/frontend/containers/NavBarContainer.js

サインアウトする前に FCM の登録トークン削除リクエストを送信するように修正しました。
(サインアウトしたことで currentUser のトークンが取れなくなってしまったために、削除リクエストが実行できなくなっていました)。

Fix sign out flow

---

app/frontend/ui/MapDetail.jsx

プライベートマップの場合は Google などの検索結果に表示されないようにしました (検索に出てきてもマップをフォローしていない限りは中を除くことはできません)。

Prevent index if map is private

---

app/frontend/ui/Discover.jsx

画面サイズが小さいときにピックアップのマップの名前が隠れてしまう問題を修正しました。

Tweak typography

---

app/frontend/containers/ExpandMapSummaryButtonContainer.js
app/frontend/containers/NavBarContainer.js
app/frontend/ui/ExpandMapSummaryButton.jsx
app/frontend/ui/MapBottomSeat.jsx
app/frontend/ui/MapDetail.jsx
app/frontend/ui/NavBar.jsx

* iOS 端末 (のブラウザ全般) で、Map Summary を開くボタンがマップの下に隠れてしまっていた問題を修正しました。
* PC 版の Navbar 上の通知欄で、画像をクリックしても対象のリソースのページに遷移しない問題を修正しました。

Fix open map summary button

---

package.json
yarn.lock

最新バージョンでもやっぱり `animateHeight` の高さの計算が直っていなかったので戻す。

Fix react-swipeable-views v0.12.14

---

app/frontend/containers/MapDetailContainer.js
app/frontend/containers/MapReviewsListContainer.js
app/frontend/containers/MapSummaryContainer.js
app/frontend/ui/MapDetail.jsx
app/frontend/ui/MapReviewsList.jsx

子コンポーネントをマウントしたタイミングではなく、親のマップ詳細画面をマウントしたタイミングでマップ下のレビュー一覧を取得するように修正しました。
※ モバイル画面で子コンポーネントがマウントされず、スポットカードを開いたときにコンテンツが表示されなくなっていました。

Fetch map reviews on page mounted

---

app/frontend/ui/MapSummary.jsx

facebook / twitter シェアボタンにカーソルを合わせたときに pointer にならない問題を修正しました (PC 版)。

Fix share button to use IconButton

---

app/frontend/ui/MapSummary.jsx

モバイル画面でマップサマリーを開いたときに、SNS シェアボタンが中央寄りに配置されるように修正しました。

Justify share button center

---

cloudbuild.yaml

base64 エンコーディングした FIREBASE_TOKEN を復号化〜環境変数として利用するように修正しました。
https://cloud.google.com/cloud-build/docs/how-to/using-encrypted-resources?hl=ja

Use secret env on cloud build

---

app/frontend/ui/Maps.jsx
app/frontend/ui/Profile.jsx

animateHeight を使っていると高さの計算がバグっているのかコンテンツが隠れてしまうという問題が起きていたので使わないようにしました。

Remove animateHeight

---

webpack.config.js

webpack 実行時に削除する古い bundle ファイルのパスが更新されていなかったので修正しました。

Clean old bundle

---

app/frontend/containers/MapDetailContainer.js
app/frontend/ui/App.jsx
app/frontend/ui/MapDetail.jsx
app/frontend/ui/SharedDialogs.jsx
app/frontend/ui/SpotCard.jsx
package.json
yarn.lock

* マップサマリー及びスポットカードを Swipeable にした結果、カード内コンテンツをスクロールできなくなってしまったため、泣く泣く Swipeable を廃止しました。
* Dialog + Menu を開いた状態でさらに上に Dialog を開こうとすると JS エラーになるという問題が発覚したため、Material-UI のバージョンを v3.2.2 まで戻しました。

Material-UI v3.2.2

---

firebase.json

firebase hosting で配信している JS ファイルについて、86400 秒キャッシュされるようにしました。

Set Cache-Ctrl of JS files

---

firebase.json

JS ファイルをキャッシュしておく期間を 1 日 → 30 日に延長しました。
ハッシュ値をつけているのでファイルが更新されれば再取得されます。

Extend cashing period

---

app/frontend/ui/GMap.jsx

共同編集タイプのマップを開いた際に、マップをフォローしていなくてもレポート作成ボタンが活性化してしまう問題を修正しました。

Fix condition for activation of create review button

---

src/frontend/components/organisms/MapReviewsList.js

マップサマリーのレポート一覧をタップしても何も起きない問題を修正しました。

Fix bug on map reviews list

---

src/frontend/components/organisms/SpotCard.js

スポットカードを開いた状態でレポートダイアログを開くと、レポートがスクロールできなくなる問題を修正しました。

Fix scrolling review dialog

---

src/frontend/components/Routes.js
src/frontend/components/organisms/IssueDialog.js
src/frontend/components/organisms/ReviewDialog.js

* モバイル時のレポートダイアログについて、画面右側からスライド表示するようにしました。
* レポートダイアログを閉じるボタンを矢印に変更しました。
* レポートダイアログの開いた際にページタイトルが更新されてしまう問題を修正しました。

Fix transition of Review dialog

---

src/frontend/components/organisms/MapSummary.js

Swipeable Views を使った場合、画像を含めた適切な高さの計算が行われないため、大量の余白が発生するという問題が起きていました。
そのため、Map Summary では Swipeable Views を使わないようにしました (ボタンタップでタブを切り替える方式にしました)。

Disable swipe on Map Summary

---

src/frontend/utils/initializeFirebaseApp.js
src/service_workers/firebase-messaging-sw.js

* プッシュ通知の処理は Service Worker 側で集中して行うようにしました (クライアント側での処理を廃止しました)。
* FCM の `setBackgroundMessageHandler ` ではなく、Service Worker で `push` イベントを拾ってプッシュ通知の処理を行うようにしました。

Refactoring: Messaging

---

cloudbuild.yaml

Cloud Build 上で yarn install する際に、engines 指定 (node: 10) を無視するようにしました。

Ignore node engines on Cloud Build

---

functions/package.json
functions/yarn.lock

cloud functions の依存ライブラリとして dotenv を使用していたところを誤って削除してしまっていたのでもとに戻しました。

Use dotenv on cloud functions

---

src/frontend/components/organisms/AnnouncementDialog.js

運営からの各お知らせのタイトルに、お知らせ詳細ページへのリンクを設定しました (リンク先は Facebook ページを想定)。

Add link on announcement

---

functions/server/utils/isBot.js

googlebot は JS を実行してくれるものの、react-helmet (JS) による head タグ内の変更は検知できていないようで、検索結果に meta タグおよび title タグを正しく反映できていませんでした。
そのため、googlebot に対しても他の bot と同様に、サーバサイドで生成した metadata.html を返すようにしました。

Add googlebot to bot list

---

src/frontend/components/Routes.js
src/frontend/components/molecules/MapToolbar.js
src/frontend/components/organisms/NavToolbar.js

初回ロード → レポート等 URL 付きのダイアログを開く → ダイアログを閉じる → 「戻る」ボタンを押したときに、戻るボタンが効かなくなる問題を修正しました。

Fix goback button

---

firebase.json
functions/server/index.js

Rendertron を使って dynamic rendering を実施するようにしました (FB/Twitter/Slack 等 bot 対策)。
https://webmaster-ja.googleblog.com/2019/01/dynamic-rendering-with-rendertron.html
https://github.com/GoogleChrome/rendertron
Cloud Function 上で rendertron-middleware を使うと、リクエスト元の host が Cloud Function のエンドポイント (*.cloudfunctions.net) になってしまって正常にレンダリングされないので、middleware を使わずに直接 fetch で叩く形式にしました。
https://github.com/justinribeiro/pwa-firebase-functions-botrender/blob/master/functions/index.js

Introduce Rendertron

---

src/frontend/components/molecules/CreateReviewTile.js
src/frontend/components/molecules/LocationButton.js
src/frontend/components/molecules/MapShareMenu.js
src/frontend/components/molecules/MapToolbar.js
src/frontend/components/molecules/ReactionsCount.js
src/frontend/components/molecules/ReviewCard.js
src/frontend/components/molecules/SharedLikeActions.js
src/frontend/components/organisms/CreateActions.js
src/frontend/components/organisms/GMap.js
src/frontend/components/organisms/MapSpotDrawer.js
src/frontend/components/organisms/MapSummary.js
src/frontend/components/organisms/RecentReviews.js
src/frontend/components/organisms/ReviewDialog.js
src/frontend/components/organisms/ReviewTiles.js
src/frontend/components/organisms/SpotDialog.js
src/frontend/components/organisms/SpotHorizontalList.js
src/frontend/components/pages/MapDetail.js
src/frontend/locales/en.json
src/frontend/locales/ja.json
src/frontend/reducers/spotDetailReducer.js

* タブレットサイズの端末ではモバイル版の UI を表示するようにしました。
* マップ画面下部のスポット一覧表示エリアについて、スポット≒レポートが 1 件もない場合はレポート投稿ボタンを表示するようにしました。
* スポットダイアログを開いたあとでレポート投稿ボタンを開くと、スポットが固定されてしまう問題を修正しました。
* レポートのタイル上にカーソルをかざすとスポット名が表示されるようにしました。
* マップツールバーの各種ボタンに Tooltip を表示するようにしました。
* ダイアログを開いたときに GA にアクションが記録されるようにしました。
* 「見つける」ページの最近のレポートのカードのデザインを新しくしました。

Tablet mobile UI

---

src/frontend/components/organisms/ReviewDialog.js

レポートダイアログを開いた際にマップの中心を対象のスポットに移動する機能が失われていたので復活させました。

Revert: Move to spot on entered review dialog

---

package.json
yarn.lock

最新の Material-UI (v4.7.2) では SwipeableDrawer の問題により MapSpotDrawer が swipe できなくなっていたのでバージョンをもとに戻しました。

Material-UI v4.3.3

---

src/frontend/components/molecules/BackButton.js
src/frontend/reducers/sharedReducer.js

ページ履歴がない場合は「戻る」ボタンを押したときにトップページに移動すべきところ、ブラウザバックしてしまっていた問題を修正しました。

Fix back button

---

src/service_workers/sw.js
webpack.config.js

Express の設定で index.html は動的に返す設定としていたのですが、workbox の挙動により `/` にアクセスしたときだけ index.html のキャッシュにアクセスしてしまっていたので修正しました。
https://developers.google.com/web/tools/workbox/modules/workbox-precaching
```
Directory Index
Requests ending in a / will, by default, be matched against entries with an index.html appended to the end. This means an incoming request for / can automatically be handled with the precached entry /index.html.
You can alter this to something else, or disable it completely, by setting directoryIndex:
```

Directory loading index.html without cache

---

src/reducers/metadataReducer.js
src/sw.js

- 意図せず noindex が付与されていたので修正
- 最新の workbox では `self.__precacheManifest` が不要だったので削除

Fix noindex

---

src/components/molecules/BackButton.js

rize-router を更新したことで、初回ロード時に 2 回 history がカウントされるようになった。
これに伴い、戻るボタンの挙動を修正する必要があった。

Fib back button behavior

---

index.js

Rendertron によるダイナミックレンダリング時に viewport のサイズを指定していなかったため、モバイルフレンドリーテストで PC 版の画面がレンダリングされ、文字が小さすぎる旨のアラートがデていたので viewport を指定するようにしました。
iPhone X のサイズを指定 (365 * 812)。

Specify width & height for Rendertron
